name: Auto Merge Template Sync PR
on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  check_suite:
    types:
      - completed
jobs:
  automerge:
    runs-on: ubuntu-latest

    steps:
      - id: automerge
        name: automerge
        uses: "pascalgn/automerge-action@v0.15.3"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          MERGE_LABELS: "template-sync"
          MERGE_REMOVE_LABELS: ""
          MERGE_METHOD: "squash"
          MERGE_COMMIT_MESSAGE: "Auto merge {pullRequest.number} from Template Sync"
          MERGE_FILTER_AUTHOR: "github-actions[bot]"
          MERGE_FORKS: "false"
          MERGE_RETRIES: "6"
          MERGE_RETRY_SLEEP: "5000"
          MERGE_DELETE_BRANCH: "true"
          MERGE_ERROR_FAIL: "true"
          UPDATE_LABELS: "template-sync"
          UPDATE_METHOD: "rebase"